#!/bin/bash

find . -name "__pycache__" -exec rm -r "{}" \;
echo "Database is kept in memory (/dev/shm/) and is not written to disk in development mode."
mkdir /dev/shm/camsdb
ln -s /dev/shm/camsdb/ data
python3 -B -m flask run
