# CAMS - CTCL 2017-2023 - Generated by Django
# Date: June 6, 2023 - June 25, 2023
# Purpose: WSGI config

"""
WSGI config for cams project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'cams.settings')

application = get_wsgi_application()
