# ---
# THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT
# ---
# CAMS Software
# Purpose: Python class representation of database tables
# Generated: February 22, 2023

from sqlalchemy import Column, ForeignKey, Integer, String, Text, create_engine
from sqlalchemy.orm import declarative_base
import hashlib

engine = create_engine("sqlite:///data/data.db")

Base = declarative_base()

# Hard-coded user class
class User(Base):
    __tablename__ = 'user'
    id = Column(Integer, primary_key=True)
    name = Column(Text)
    password = Column(Text)

    def verify_password(self, password):
        h = hashlib.sha512()
        h.update(password)
        pwhash = hexdigest
        return self.password == pwhash

Base.metadata.create_all(engine)
