# ---
# THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT
# ---
# CAMS Software
# Purpose: Python class representation of database models
# Generated: February 11, 2023

from sqlalchemy import Column, ForeignKey, Integer, String
from sqlalchemy.orm import declarative_base

Base = declarative_base()
class user(Base):
    __tablename__ = "user"
    inid = Column(Integer, primary_key=True)